src_dir: "/Users/ankul/obsidian"
template_dir: "/Users/ankul/obsidian/_template/ALL.md"
report_file: "/Users/ankul/obsidian/_report/close_reports.md"
log_level: "info"
concurrency_limit: 12
skip_patterns:
  - "."
  - "_"
  - "any"
